In [1]:
import pandas as pd

In [2]:
human_csv = pd.read_csv("data/human_res.csv")
human_csv

,Person,Article 1 (msn) Score,Article 2 (onion) Score,Article 3 (cnn) Score,Article 4 (fact check) Score
0,Calvin,2,7,3,1
1,Samantha,4,9,1,2
2,Person A,7,5,1,8
3,Person B,1,9,4,3

In [3]:
human_data = human_csv[~human_csv.iloc[:, 1].isnull()]
human_data

,Person,Article 1 (msn) Score,Article 2 (onion) Score,Article 3 (cnn) Score,Article 4 (fact check) Score
0,Calvin,2,7,3,1
1,Samantha,4,9,1,2
2,Person A,7,5,1,8
3,Person B,1,9,4,3

In [4]:
genai_csv = pd.read_csv("data/gen_ai_res.csv")
genai_csv.head()

,Prompting Type,Adjustment Made,Prompt being used,Article 1 (msn) Score,Response,VB Response,SERP Response,Article 2 (onion) Score,Response.1,VB Response.1,SERP Response.1,Article 3 (cnn) Score,Response.2,VB Response.2,SERP Response.2,Article 4 (fact check) Score,Response.3,VB Response.3,SERP Response.3
0,Normal Prompting,NaN,"Given the inputted article, rate it based on n...",1.0,**Paragraph 1:** Introduces the event and rais...,NaN,NaN,9.0,**Paragraph 1:** Presents a plan for mass depo...,NaN,NaN,2.0,**Paragraph 1:**\r\n\r\n* **Perspective check:...,NaN,NaN,1.0,**Paragraph 1:** Introduces the topic and sets...,NaN,NaN
1,Normal Prompting,Vector Database (VB),"Given the inputted article, rate it based on n...",4.2,**Paragraph 1:** Introduces the event and rais...,"ChromaDB Info: Based on the headline, these ar...",NaN,8.5,**Paragraph 1:**\r\n\r\n* **Perspective check:...,"ChromaDB Info: Based on the headline, these ar...",NaN,7.5,**Paragraph 1:**\r\n\r\n* **Perspective check:...,"ChromaDB Info: Based on the headline, these ar...",NaN,2.0,**Paragraph 1:** Introduces the topic and sets...,"ChromaDB Info: Based on the headline, these ar...",NaN
2,Normal Prompting,Serp API,"Given the inputted article, rate it based on n...",2.0,Paragraph 1: Presents the event and raises que...,NaN,SERP API: These are similar articles found onl...,1.0,**Paragraph 1:** Presents a satirical list of ...,NaN,SERP API: These are similar articles found onl...,7.5,**Paragraph 1 Analysis:**\r\n\r\n* **Perspecti...,NaN,SERP API: These are similar articles found onl...,1.0,**Paragraph 1:** Introduces the topic and sets...,NaN,SERP API: These are similar articles found onl...
3,Normal Prompting,Function Calling (FC),"Given the inputted article, rate it based on n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Normal Prompting,VB and Serp,"Given the inputted article, rate it based on n...",6.5,**Paragraph 1: Naive Realism Analysis**\n\n* *...,"ChromaDB Info: Based on the headline, these ar...",SERP API: These are similar articles found onl...,7.0,**Paragraph 1:** Presents the plan for mass de...,"ChromaDB Info: Based on the headline, these ar...",SERP API: These are similar articles found onl...,2.5,**Paragraph 1:**\n\n* **Perspective check:** T...,"ChromaDB Info: Based on the headline, these ar...",SERP API: These are similar articles found onl...,1.0,**Paragraph 1:** Introduces the topic and sets...,"ChromaDB Info: Based on the headline, these ar...",SERP API: These are similar articles found onl...

In [5]:
genai_data = genai_csv[~genai_csv.iloc[:, 3].isnull()]
genai_data.shape
# 3 different prompting types * 4 adjustment types = 12

(12, 19)

In [6]:
article_scores = human_data.iloc[:, 1:].mean()
article_scores

Article 1 (msn) Score           3.50
Article 2 (onion) Score         7.50
Article 3 (cnn) Score           2.25
Article 4 (fact check) Score    3.50
dtype: float64

In [7]:
article_scores.iloc[0]

3.5

In [8]:
genai_data_scores_only = genai_data[["Prompting Type", "Adjustment Made", "Article 1 (msn) Score" , "Article 2 (onion) Score", "Article 3 (cnn) Score", "Article 4 (fact check) Score"]]
genai_data_scores_only

,Prompting Type,Adjustment Made,Article 1 (msn) Score,Article 2 (onion) Score,Article 3 (cnn) Score,Article 4 (fact check) Score
0,Normal Prompting,NaN,1.0,9.0,2.0,1.00
1,Normal Prompting,Vector Database (VB),4.2,8.5,7.5,2.00
2,Normal Prompting,Serp API,2.0,1.0,7.5,1.00
4,Normal Prompting,VB and Serp,6.5,7.0,2.5,1.00
8,Chain of Thought,NaN,1.0,1.0,9.5,1.50
9,Chain of Thought,Vector Database (VB),3.5,1.0,9.5,1.00
10,Chain of Thought,Serp API,3.5,8.5,9.5,1.50
12,Chain of Thought,VB and Serp,2.0,1.0,9.0,1.00
16,Fractal Chain of Thought,NaN,5.0,2.0,2.0,2.33
17,Fractal Chain of Thought,Vector Database (VB),5.0,2.0,8.5,6.00
18,Fractal Chain of Thought,Serp API,6.5,1.0,1.0,4.00
20,Fractal Chain of Thought,VB and Serp,7.8,3.0,9.0,4.00

In [9]:
def mae(row):
    sum_ae = 0
    for i in ["Article 1 (msn) Score", "Article 2 (onion) Score", "Article 3 (cnn) Score", "Article 4 (fact check) Score"]:
        prompt_score = row.loc[i] 
        article_score = article_scores.loc[i]
        ae = abs(prompt_score - article_score)
        sum_ae += ae
    mae = sum_ae / 4
    return mae

In [10]:
genai_data_scores_only['MAE'] = genai_data_scores_only.apply(mae, axis=1)
genai_data_scores_only

/tmp/ipykernel_377/2321417623.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genai_data_scores_only['MAE'] = genai_data_scores_only.apply(mae, axis=1)

,Prompting Type,Adjustment Made,Article 1 (msn) Score,Article 2 (onion) Score,Article 3 (cnn) Score,Article 4 (fact check) Score,MAE
0,Normal Prompting,NaN,1.0,9.0,2.0,1.00,1.6875
1,Normal Prompting,Vector Database (VB),4.2,8.5,7.5,2.00,2.1125
2,Normal Prompting,Serp API,2.0,1.0,7.5,1.00,3.9375
4,Normal Prompting,VB and Serp,6.5,7.0,2.5,1.00,1.5625
8,Chain of Thought,NaN,1.0,1.0,9.5,1.50,4.5625
9,Chain of Thought,Vector Database (VB),3.5,1.0,9.5,1.00,4.0625
10,Chain of Thought,Serp API,3.5,8.5,9.5,1.50,2.5625
12,Chain of Thought,VB and Serp,2.0,1.0,9.0,1.00,4.3125
16,Fractal Chain of Thought,NaN,5.0,2.0,2.0,2.33,2.1050
17,Fractal Chain of Thought,Vector Database (VB),5.0,2.0,8.5,6.00,3.9375
18,Fractal Chain of Thought,Serp API,6.5,1.0,1.0,4.00,2.8125
20,Fractal Chain of Thought,VB and Serp,7.8,3.0,9.0,4.00,4.0125

In [11]:
genai_data_scores_only.sort_values(by="MAE", ascending=True)

,Prompting Type,Adjustment Made,Article 1 (msn) Score,Article 2 (onion) Score,Article 3 (cnn) Score,Article 4 (fact check) Score,MAE
4,Normal Prompting,VB and Serp,6.5,7.0,2.5,1.00,1.5625
0,Normal Prompting,NaN,1.0,9.0,2.0,1.00,1.6875
16,Fractal Chain of Thought,NaN,5.0,2.0,2.0,2.33,2.1050
1,Normal Prompting,Vector Database (VB),4.2,8.5,7.5,2.00,2.1125
10,Chain of Thought,Serp API,3.5,8.5,9.5,1.50,2.5625
18,Fractal Chain of Thought,Serp API,6.5,1.0,1.0,4.00,2.8125
2,Normal Prompting,Serp API,2.0,1.0,7.5,1.00,3.9375
17,Fractal Chain of Thought,Vector Database (VB),5.0,2.0,8.5,6.00,3.9375
20,Fractal Chain of Thought,VB and Serp,7.8,3.0,9.0,4.00,4.0125
9,Chain of Thought,Vector Database (VB),3.5,1.0,9.5,1.00,4.0625
12,Chain of Thought,VB and Serp,2.0,1.0,9.0,1.00,4.3125
8,Chain of Thought,NaN,1.0,1.0,9.5,1.50,4.5625

Normal Prompting with no adjustment seem to get the best results without any adjustments surprisingly. They seem to match what we think about naive realism. However, it could be because our sample is small, as I thought the model was thinking more with fractal chain of thought. Normal Prompting is the top 3 in MAE.

In [12]:
def mean_prompts(row):
    total_sum = 0
    for i in ["Article 1 (msn) Score", "Article 2 (onion) Score", "Article 3 (cnn) Score", "Article 4 (fact check) Score"]:
        prompt_score = row.loc[i] 
        total_sum += prompt_score
    mean_prompt = total_sum / 4
    return mean_prompt

In [13]:
genai_data_scores_only['mean_of_prompts'] =  genai_data_scores_only.apply(mean_prompts, axis=1)
genai_data_scores_only

/tmp/ipykernel_377/386021742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genai_data_scores_only['mean_of_prompts'] =  genai_data_scores_only.apply(mean_prompts, axis=1)

,Prompting Type,Adjustment Made,Article 1 (msn) Score,Article 2 (onion) Score,Article 3 (cnn) Score,Article 4 (fact check) Score,MAE,mean_of_prompts
0,Normal Prompting,NaN,1.0,9.0,2.0,1.00,1.6875,3.2500
1,Normal Prompting,Vector Database (VB),4.2,8.5,7.5,2.00,2.1125,5.5500
2,Normal Prompting,Serp API,2.0,1.0,7.5,1.00,3.9375,2.8750
4,Normal Prompting,VB and Serp,6.5,7.0,2.5,1.00,1.5625,4.2500
8,Chain of Thought,NaN,1.0,1.0,9.5,1.50,4.5625,3.2500
9,Chain of Thought,Vector Database (VB),3.5,1.0,9.5,1.00,4.0625,3.7500
10,Chain of Thought,Serp API,3.5,8.5,9.5,1.50,2.5625,5.7500
12,Chain of Thought,VB and Serp,2.0,1.0,9.0,1.00,4.3125,3.2500
16,Fractal Chain of Thought,NaN,5.0,2.0,2.0,2.33,2.1050,2.8325
17,Fractal Chain of Thought,Vector Database (VB),5.0,2.0,8.5,6.00,3.9375,5.3750
18,Fractal Chain of Thought,Serp API,6.5,1.0,1.0,4.00,2.8125,3.1250
20,Fractal Chain of Thought,VB and Serp,7.8,3.0,9.0,4.00,4.0125,5.9500

In [14]:
genai_data_scores_only.sort_values(by="mean_of_prompts", ascending=False)

,Prompting Type,Adjustment Made,Article 1 (msn) Score,Article 2 (onion) Score,Article 3 (cnn) Score,Article 4 (fact check) Score,MAE,mean_of_prompts
20,Fractal Chain of Thought,VB and Serp,7.8,3.0,9.0,4.00,4.0125,5.9500
10,Chain of Thought,Serp API,3.5,8.5,9.5,1.50,2.5625,5.7500
1,Normal Prompting,Vector Database (VB),4.2,8.5,7.5,2.00,2.1125,5.5500
17,Fractal Chain of Thought,Vector Database (VB),5.0,2.0,8.5,6.00,3.9375,5.3750
4,Normal Prompting,VB and Serp,6.5,7.0,2.5,1.00,1.5625,4.2500
9,Chain of Thought,Vector Database (VB),3.5,1.0,9.5,1.00,4.0625,3.7500
0,Normal Prompting,NaN,1.0,9.0,2.0,1.00,1.6875,3.2500
8,Chain of Thought,NaN,1.0,1.0,9.5,1.50,4.5625,3.2500
12,Chain of Thought,VB and Serp,2.0,1.0,9.0,1.00,4.3125,3.2500
18,Fractal Chain of Thought,Serp API,6.5,1.0,1.0,4.00,2.8125,3.1250
2,Normal Prompting,Serp API,2.0,1.0,7.5,1.00,3.9375,2.8750
16,Fractal Chain of Thought,NaN,5.0,2.0,2.0,2.33,2.1050,2.8325